#!/usr/bin/php
<?php

$phase = 4;
$category_list = [
  'cdtt',
  'choice_rt',
  'ecg',
  'frax',
  'f_word_fluency',
  'a_word_fluency',
  's_word_fluency',
  'alphabet',
  'mental_alternation',
  'animal_fluency',
  'counting',
  'delayed_word_list',
  'immediate_word_list',
  'stroop_dot',
  'stroop_word',
  'stroop_colour',
  'spirometry_flow',
  'spirometry_volume',
  'spirometry_report',
];

foreach( $category_list as $category )
{
  passthru( sprintf( 'php /usr/local/lib/data_librarian/get_opal_data.php %d %s', $phase, $category ) );
}
