#!/usr/bin/php
<?php
/**
 * A script that downloads all new binary data from Opal
 * This is a temporary script that will be run on a regular basis until binary data is no longer
 * uploaded to Opal.  After that time it will no longer be required.
 */

$phase = 4;
$category_list = [
  'cdtt',
  'choice_rt',
  'ecg',
  'frax',
  'f_word_fluency',
  'a_word_fluency',
  's_word_fluency',
  'alphabet',
  'mental_alternation',
  'animal_fluency',
  'counting',
  'delayed_word_list',
  'immediate_word_list',
  'stroop_dot',
  'stroop_word',
  'stroop_colour',
  'spirometry_flow',
  'spirometry_volume',
  'spirometry_report',
];

foreach( $category_list as $category )
{
  passthru( sprintf( 'php /usr/local/lib/data_librarian/get_opal_data.php -p %d %s', $phase, $category ) );
}
